set -e

## edk2
cd edk2
source ./edksetup.sh > /dev/null
sed -ie '/ACTIVE_PLATFORM/ s/=.*$/= hoge\/fuga.dsc/g;
         /TARGET_ARCH/ s/=.*$/= X64/g;
         /TOOL_CHAIN_TAG/ s/=.*$/= CLANG38/g' Conf/target.txt
sed -ie '/CLANG38/ s/-flto//g' Conf/tools_def.txt
cd ..

set +e
